name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Create deployment package
        run: |
          tar --exclude=content --exclude=media --exclude=site/config --exclude=storage \
              -czf deploy.tar.gz .

      - name: Copy files to server via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "deploy.tar.gz"
          target: "${{ secrets.SSH_TARGET_DIR }}"

      - name: Extract files on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.SSH_TARGET_DIR }}
            tar -xzf deploy.tar.gz
            rm deploy.tar.gz
